version: "3.9"

services:
  motion-index-api:
    container_name: motion-index-api
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ../../.env
    restart: unless-stopped
    # Mount source for easier local iteration (manual restart required)
    volumes:
      - ../../:/app

