name: motion-index-fiber
region: nyc

services:
  - name: api
    source_dir: .
    environment_slug: go
    instance_size_slug: basic-xxs
    instance_count: 1

    # App Platform injects PORT (typically 8080) at runtime.
    # Our server reads PORT from env, so we just expose the same http_port here.
    http_port: 8080

    # Run the server directly (no custom build step required)
    run_command: go run cmd/server/main.go

    routes:
      - path: /

    # Optional, but recommended
    health_check:
      path: /health

    envs:
      # Core environment
      - key: ENVIRONMENT
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PRODUCTION
        value: "true"
        scope: RUN_AND_BUILD_TIME

      # CORS
      - key: ALLOWED_ORIGINS
        value: https://your-frontend.example.com
        scope: RUN_TIME

      # Authentication (required)
      - key: JWT_SECRET
        type: SECRET
        value: ""
      - key: SUPABASE_URL
        value: https://your-project.supabase.co
        scope: RUN_TIME
      - key: SUPABASE_ANON_KEY
        type: SECRET
        value: ""
      - key: SUPABASE_SERVICE_KEY
        type: SECRET
        value: ""

      # DigitalOcean Spaces (required in non-local env)
      - key: DO_SPACES_ACCESS_KEY
        type: SECRET
        value: ""
      - key: DO_SPACES_SECRET_KEY
        type: SECRET
        value: ""
      - key: DO_SPACES_BUCKET
        value: motion-index-docs
        scope: RUN_TIME
      - key: DO_SPACES_REGION
        value: nyc3
        scope: RUN_TIME
      # Optional CDN endpoint (if you have a CDN-enabled Space)
      - key: DO_SPACES_CDN_ENDPOINT
        value: ""
        scope: RUN_TIME

      # DigitalOcean OpenSearch (required in non-local env)
      - key: DO_OPENSEARCH_HOST
        value: your-opensearch-cluster.k.db.ondigitalocean.com
        scope: RUN_TIME
      - key: DO_OPENSEARCH_PORT
        value: "25060"
        scope: RUN_TIME
      - key: DO_OPENSEARCH_USERNAME
        type: SECRET
        value: ""
      - key: DO_OPENSEARCH_PASSWORD
        type: SECRET
        value: ""
      - key: DO_OPENSEARCH_USE_SSL
        value: "true"
        scope: RUN_TIME

      # DigitalOcean API token (required in non-local env by the DO integration layer)
      - key: DO_API_TOKEN
        type: SECRET
        value: ""

      # AI provider keys (optional)
      - key: OPENAI_API_KEY
        type: SECRET
        value: ""
      - key: CLAUDE_API_KEY
        type: SECRET
        value: ""

      # Tuning knobs (optional)
      - key: MAX_REQUEST_SIZE
        value: "104857600"   # 100MB
        scope: RUN_TIME
      - key: MAX_FILE_SIZE
        value: "104857600"   # 100MB
        scope: RUN_TIME
      - key: MAX_WORKERS
        value: "10"
        scope: RUN_TIME
      - key: BATCH_SIZE
        value: "50"
        scope: RUN_TIME
      - key: PROCESS_TIMEOUT
        value: 5m
        scope: RUN_TIME